### ISSUE TITLE
Automatic Weight Entry?

### ISSUE THREAD

**Issue by bmwhiteh** [tooanalytical/GreenwaySeniorDesignProject#49]
![img_0705](https://user-images.githubusercontent.com/22662346/38399869-f73f32b8-391a-11e8-857d-a20da98bd965.PNG)

I chose to not enter any of this data yet it assigned a weight of 150lbs and a 0feet 0 inches height (not shown but did happen).

**Comment by tooanalytical** [comment]
This is hard coded into the application otherwise the user will not get calories burned data and it will break the script with NAN. Thank you for bringing it to attention, but not a bug.

**Comment by tooanalytical** [comment]
Good point. I'll modify the text on the page to reflect that.
