### ISSUE TITLE
Profile Picture NOT optional

### ISSUE THREAD

**Issue by bmwhiteh** [tooanalytical/GreenwaySeniorDesignProject#51]
![img_0706](https://user-images.githubusercontent.com/22662346/38399935-5bab4be2-391b-11e8-8f24-dd79188ccc9f.PNG)

Issue: The screen says that a Profile Picture is "optional" however I was not able to move past this screen without putting an image in there. The database connection puts a "default avatar" in for any images that don't come through from mobile.

**Comment by tooanalytical** [comment]
Good find. Fixed and pushed to repo.
