### ISSUE TITLE
GNU License Link

### ISSUE THREAD

**Issue by bmwhiteh** [tooanalytical/GreenwaySeniorDesignProject#55]
![img_0711](https://user-images.githubusercontent.com/22662346/38400082-48ef8e54-391c-11e8-84ac-8161b5bed955.PNG)

Issue: If you click the hyperlink on the "About Page" to view the public license (shown), Viridian does not supply a back button and the app must be physically stopped in order to use the app.

**Comment by tooanalytical** [comment]
Good catch. Fixed and pushed to repo. Closed.
