### ISSUE TITLE
Account Statistics

### ISSUE THREAD

**Issue by bmwhiteh** [tooanalytical/GreenwaySeniorDesignProject#59]
![img_08232](https://user-images.githubusercontent.com/22662346/38400485-311bb760-391e-11e8-82b0-dad31da0d5c4.jpg)

Issue: Account Statistics are still largely incorrect.

**Comment by andreamoorman** [comment]
I went through every open issue multiple times and I see nothing about this.

**Comment by andreamoorman** [comment]
I don't believe this issue was regarding the incorrect distance. It was regarding the fact that, for example: when the calories for each type of activity are summed, the number displayed is incorrect ( 0 + 3071 + 0 does not, in fact, equal 48.74)

**Comment by tooanalytical** [comment]
There are no calculations on this page as everything is returned from the server as a JSON and is displayed without modification. If you believe the server's JSON to be incorrect I would advise you open a ticket for a review of that script on the server.

**Comment by andreamoorman** [comment]
It's still a bug that affects the mobile end users, and should be noted here, until resolved.

**Comment by tooanalytical** [comment]
Then it is assigned to you and Bailey. Mark it closed when resolved.
