### ISSUE TITLE
Location Tracking occurs whenever app is running

### ISSUE THREAD

**Issue by bmwhiteh** [tooanalytical/GreenwaySeniorDesignProject#69]
![img_0722](https://user-images.githubusercontent.com/22662346/38417075-fcd6b3a0-3964-11e8-9906-f6f1888ff238.PNG)

Issue: GPS Location coordinates are sent to the database whenever the app is running (either in background or open) regardless of if they are actively tracking an activity. The track_location.php database connection script is receiving requests without an activityId any time that the app is open. Below is a screenshot of the database. These track_location.php requests were sent to the database when my iPad was sitting next to me with the app on the activity history page as I was writing down bug notes. I ran several activity tests prior to noticing this however the activity tracker requires you to end the activity before navigating away from the tracker page. 5 track_location.php requests were submitted when the open iPhone 6S was picked up and looked at alone. 

![](https://files.slack.com/files-pri/T5QNXE3RN-FA2AVSMRB/image.png)

**Comment by tooanalytical** [comment]
Application only tracks location after a user has started an activity on the Record Activity page. Found location .unsubscribe() bug where the report user location function did not stop after user stopped activity. Implemented fix and pushed to repo.

**Comment by tooanalytical** [comment]
Fixed with 0.0.9. Closed
